#!/usr/bin/env python3
import argparse

from dnsservermanager import dnsservermanager


def dns_server():

    parser = argparse.ArgumentParser(description='dns')
    parser.add_argument('-p')
    parser.add_argument('-n')

    args = parser.parse_args()
    port = int(args.p)
    client = dnsservermanager(args.n, port)
    client.listen()


if __name__ == '__main__':
    dns_server()
