#!/bin/bash

while getopts p:o:n:u:i: flag
do
  case "${flag}" in
    p) port=${OPTARG};;
    o) origin=${OPTARG};;
    n) name=${OPTARG};;
    u) username=${OPTARG};;
    i) keyfile=${OPTARG};;
  esac
done

#echo "$port";
#echo "$origin";
#echo "$name";
#echo "$username";
#echo "$keyfile";


curl "http://p5-http-a.5700.network:$port/kill"
curl "http://p5-http-b.5700.network:$port/kill"
curl "http://p5-http-c.5700.network:$port/kill"
curl "http://p5-http-d.5700.network:$port/kill"
curl "http://p5-http-e.5700.network:$port/kill"
curl "http://p5-http-f.5700.network:$port/kill"
curl "http://p5-http-g.5700.network:$port/kill"

ssh -i "$keyfile" -t "$username"@p5-http-a.5700.network 'rm httpserver'
ssh -i "$keyfile" -t "$username"@p5-http-b.5700.network 'rm httpserver'
ssh -i "$keyfile" -t "$username"@p5-http-c.5700.network 'rm httpserver'
ssh -i "$keyfile" -t "$username"@p5-http-d.5700.network 'rm httpserver'
ssh -i "$keyfile" -t "$username"@p5-http-e.5700.network 'rm httpserver'
ssh -i "$keyfile" -t "$username"@p5-http-f.5700.network 'rm httpserver'
ssh -i "$keyfile" -t "$username"@p5-http-g.5700.network 'rm httpserver'